name: ci
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/ci.yml'
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install zensical and plugins
        run: pip install zensical markdown-include pymdown-extensions mkdocs-awesome-pages-plugin mkdocs-glightbox
        working-directory: ./docs
      - name: Build Site
        run: zensical build --clean
        working-directory: ./docs
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
