name: ci 
on:
  push:
    branches:
      - master 
    paths:
      - 'docs/**'
      - 'zensical.toml'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - name: Setup Cache
        uses: actions/cache@v4
        with:
          key: zensical-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            zensical-
      - name: Install zensical and plugins
        run: pip install markdown-include pymdown-extensions zensical mkdocs-awesome-pages-plugin mkdocs-glightbox
        working-directory: ./docs
      - name: Deploy Site
        run: zensical gh-deploy --force
        working-directory: ./docs
